# Generated by Django 5.2.5 on 2025-09-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'კატეგორიები'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
